contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
theme = "terminal"
title = "blog.siliconloons.com"

baseurl = "https://blog.siliconloons.com/"
canonifyurls = true

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "Silicon Loons"
    subtitle = "Kyle Mestery's technology commentary"
    keywords = ""
    copyright = "2019"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

  [languages.en.params.logo]
    logoText = "Silicon Loons"
    logoHomeLink = "/"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "RSS"
      name = "RSS"
      url = "/index.xml"
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
    [[languages.en.menu.main]]
      identifier = "GitHub"
      name = "github"
      url = "https://github.com/mestery"
    [[languages.en.menu.main]]
      identifier = "LinkedIn"
      name = "linkedin"
      url = "https://www.linkedin.com/pub/kyle-mestery/3/a0b/64a"
    [[languages.en.menu.main]]
      identifier = "Twitter"
      name = "twitter"
      url = "https://www.twitter.com/mestery"
